-- SafeGround Database Schema
-- =============================================================================
-- CANONICAL MIGRATION: supabase/migrations/00_full_schema.sql
-- Copy and run that entire file in Supabase SQL Editor (not this stub).
-- =============================================================================
